### ISSUE TITLE
Notes on my intentions 

### ISSUE THREAD

**Issue by prepare** [LayoutFarm/HtmlRenderer#11]
Hello
@bjorn-ali-goransson, 
and those who come from https://github.com/AngleSharp/AngleSharp.Css/issues/2

If your code meet these ...

1. No copyleft code
2. Support .Net framework >=2.0
3. No Linq

It makes me  easier to integrate your code back to my repo.

---

 
I  also **try to figure out**
_How to support more that 1 Html-Css Dom/Parser frameworks_.

eg.
1. [HtmlKit](https://github.com/jstedfast/HtmlKit) - that is used in this repo.
2. [Pasta](https://github.com/prepare/Pasta) - my unfinished port of Google's Gumbo. 
3. **[Radius](https://github.com/prepare/Radius) - attempt the bring AngelSharp to the HtmlRenderer, not finish.** 

so lets create some abstraction.

Please _**don't**_ throw other frameworks away :)

---

Feel free to create issues about the HtmlRenderer here.

**Comment by bjorn-ali-goransson** [comment]
Those constraints would be no problem, florian do you have such constraints?

Supporting several parser would definetely be possible, you just make an
abstraction layer above it.

But why, since anglesharp is the best? :smile:

No seriously, why?

Den 6 feb 2018 02:16 skrev "win" <notifications@github.com>:

**Comment by prepare** [comment]
**Why support more than 1 ?**
 

I want other C# developers who has their framework can
use the HtmlRenderer too.

I don't want them to throw their work away.

eg.

[HtmlKit](https://github.com/jstedfast/HtmlKit) code help this repo come true => I continue to support it.

or [Pasta](https://github.com/prepare/Pasta) => I want to study the Google code too ;)

**Comment by prepare** [comment]
And that is another way to ensure that the code has low dependency on others

**Comment by bjorn-ali-goransson** [comment]
HtmlKit almost looks like a SAX parser. Is it anything like traversing the DOM?

**Comment by prepare** [comment]
You can simply access each node by traveling through their DOM.

but no sophisticated traversing code now.

**Comment by bjorn-ali-goransson** [comment]
It sounds like an abstraction on top of the parsers should be simple.

**Comment by prepare** [comment]
I bind my RenderTree with the HtmlKit here...

https://github.com/LayoutFarm/HtmlRenderer/blob/master/Source/LayoutFarm.HtmlComposer/1_Composers/1_Builder/WebDocumentParser.cs

**Comment by bjorn-ali-goransson** [comment]
I find the solution to be a bit strangely organized (if not unorganized 😅)

How does one get Deps ? Why not use NuGet?....

**Comment by bjorn-ali-goransson** [comment]
For example, I now have an empty HtmlRenderer\Source\Deps\BurningMineCurve\CurveUtils, dunno how it got created.

And it gives hundreds of errors when opening the solution (of course since Deps only contains empty dirs)

[Failure] Could not find file '... HtmlRenderer\Source\Deps\BurningMineCurve\CurveUtils\VectorHelper.cs'.

**Comment by prepare** [comment]
please see this https://github.com/LayoutFarm/HtmlRenderer/blob/master/Source/Deps/README.md

**Comment by prepare** [comment]
The Rendering Part  ((https://github.com/PaintLab/PixelFarm) is a huge part,
quite complex and yes not well-organized :'(

since It is planned to support real-time HtmlRendering.
(esp. UI application / software/hardware rendering).

but once you get the PixelFarm code => all the code are there.

**Comment by prepare** [comment]
At this development stage,
you may need to see all the PixelFarm code (helping organize them too is welcome).

---

I cheer you, Don't give up with that _complex_ part!

**Comment by prepare** [comment]
I am investigating / developing more on **Radius (https://github.com/prepare/Radius)**

:)
