### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by GustavoHennig** [LayoutFarm/HtmlRenderer#17]
Hi,
I am trying to build the project and I have many broken references and there are several projects unavailable. Is this guide still valid?
https://github.com/LayoutFarm/HtmlRenderer/wiki/3.-Build-The-Project

**Comment by prepare** [comment]
@GustavoHennig 

Thank you for your interest.
That guide is too old.
I will revise it again later.

at this moment,  I provide an early help first. 

---

How to Build the HtmlRenderer 
---

2018, June

OS: Win10
Visual Studio: 2017


Screenshot step-by-step is here :)

---

**1. Clone**
I start with a folder name **'d:\\projects'**

We need 2 projects 

1) HtmlRenderer (https://github.com/LayoutFarm/HtmlRenderer, master branch)
2) PixelFarm (https://github.com/PaintLab/PixelFarm, master branch)

clone it into the d:\\projects folder

![01_started_with_proje_cts_folder](https://user-images.githubusercontent.com/7447159/41113257-5487ae98-6aab-11e8-99b9-f6a6098f0acb.png)

_pic 1: the 2 projects **must be place in the same level like this picture**, there are cross-references between them_


---

**2. Build PixelFarm**


![02_open_pixelfarm_minidev_sln](https://user-images.githubusercontent.com/7447159/41113259-54beb6f4-6aab-11e8-9464-5fdb189d44e5.png)
_pic 2: VS2017, Open that MiniDev.sln in that folder_

---
![03_build_pixelfarm](https://user-images.githubusercontent.com/7447159/41113260-54f817fa-6aab-11e8-9fb7-b9e844c68fe8.png)
_pic 3: Solution Explorer, Build All_

---
![04_pixelfarm_succeeded](https://user-images.githubusercontent.com/7447159/41113261-552c43c2-6aab-11e8-89d9-5340b24cd8fb.png)

_pic 4: Succeeded!_


---
**3. Build HtmlRenderer**

![05_build_html_renderer](https://user-images.githubusercontent.com/7447159/41113262-5566c768-6aab-11e8-8daf-2fe995766505.png)

_pic 5: Open that solution_

---
![06_build_html_renderer](https://user-images.githubusercontent.com/7447159/41113263-559c3772-6aab-11e8-8c38-1456d7137e93.png)

_pic 6: Solution Explorer, Build All_

---
![07_html_renderer_succeeded](https://user-images.githubusercontent.com/7447159/41113264-55e2a89c-6aab-11e8-8d76-1afefe18e5af.png)

_pic 7: Succeeded!_

---
**4. Test It**

![08_test3_mixhtml](https://user-images.githubusercontent.com/7447159/41113265-56186aea-6aab-11e8-93fa-51e63dd87434.png)

_pic 8: F5 on Test3_MixHtml project, click the example in the RedBox_

---

![09_acid1_sample](https://user-images.githubusercontent.com/7447159/41113266-5651a102-6aab-11e8-9a77-36b7ccd6dd97.png)

_pic 9: Acid1 test page_

---

**Comment by GustavoHennig** [comment]
Thank you, it worked!

I had to do 2 small changes to run:

- Comment the line:  CommonTextServiceSetup.cs:58 (I don't have the file: "d:/test/icu60/brkitr_src/dictionaries")
- I had to put this line in the main, due an exception in the float.parse. (In my location settings "," is the decimal separator).
`
Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");
`

**Comment by prepare** [comment]
If you want that data ...
"d:/test/icu60/brkitr_src/dictionaries" => 

It is 'raw' Icu data for text-break 

It try to look for this ...
https://github.com/PaintLab/PixelFarm/tree/dev/src/PixelFarm/Typography/Typography.TextBreak/icu61/brkitr/dictionaries

or download the original Icu data (http://cldr.unicode.org/)

**Comment by prepare** [comment]
More info about HtmlRenderer ...
https://github.com/LayoutFarm/HtmlRenderer/issues/15

**Comment by prepare** [comment]
This guide has been changed again.

Previously, the Typography lib is embeded in the PixelFarm.

Now, I spin off the Typography, and remove it from PixelFarm.

---
 When one build the PixelFarm.
You need to clone the Typography into the folder (Typography) at 
the same level as PixelFarm. (like the HtmlRenderer need the PixelFarm on the same level)

**Comment by jingyiliu** [comment]
Failed to build the Typography!
The error is found at: BitmapFontMx->ReadGlyphImages method.
It seems that a GetBuffer method is missing in type PixelFarm.CpuBlit.ActualBitmap.

**Comment by prepare** [comment]
Hello @jingyiliu 

I forget to upload latest Typography.

The error should be fixed with this https://github.com/LayoutFarm/Typography/commit/3b990f0057ff1901d10abde38a0ef15b8efa63a7

The error should be fixed with this https://github.com/LayoutFarm/Typography/commit/3b990f0057ff1901d10abde38a0ef15b8efa63a7

**Comment by jingyiliu** [comment]
It works now.
Thank you for your quick response.

**Comment by prepare** [comment]
Latest all-in-one build, see=> https://github.com/LayoutFarm/HtmlRenderer.Build
