### ISSUE TITLE
Is this cross-platform

### ISSUE THREAD

**Issue by jingyiliu** [LayoutFarm/HtmlRenderer#20]
Hi, 
Does this project support .net core now?

**Comment by prepare** [comment]
No. It dose not support .net core now.

But cross-platform is one of the goals of this project.

**Comment by jingyiliu** [comment]
why is it unportable?
i mean which part of code causes the problem?

**Comment by prepare** [comment]
Most of the code should be cross platform.

But some parts that use  extern 'DllImport' are not tested with other platform.

**Comment by prepare** [comment]
The backend rendering engine of this project is based on the PaintLab/PixelFarm project.
If it works on other platform. Then this project will work too.

Last month, I've test the rendering engine with CosmosOS see=>https://github.com/PaintLab/PixelFarm/issues/31.  

---

But I also have a plan that I should separate the layout engine from rendering engine 
see https://github.com/LayoutFarm/HtmlRenderer/issues/14 so

other users can use this as a html 'Layout' engine (Measure/ Alignment-Placement)
and  choose their own rendering engine.
