### ISSUE TITLE
demo apps not works?

### ISSUE THREAD

**Issue by Karaulov** [LayoutFarm/HtmlRenderer#22]
![b8ja1vf 1](https://user-images.githubusercontent.com/6445336/45313280-1aaa5780-b537-11e8-828c-21c64caae4e6.png)
![njcckvo 1](https://user-images.githubusercontent.com/6445336/45313297-25fd8300-b537-11e8-9507-148844d33e59.png)

**Comment by prepare** [comment]
I think the error come from 
parsing number with non-english culture-info at that error site.

1. could you please snap to errror site?

It should be fixed with parse + specific en-us culture or culture nutral

**Comment by Karaulov** [comment]
@prepare Sorry, I did not understand what you wanted. What should I do in the code?

**Comment by prepare** [comment]
I'm finding that bug. please wait

**Comment by prepare** [comment]
(ref https://stackoverflow.com/questions/147801/best-way-to-parse-float)

please try fixing that
by find this file and fixed it like this


https://github.com/PaintLab/PixelFarm/commit/fb1b77391493649954112e7b9575bc2b2ec13a59

Let me know if it work or not

**Comment by Karaulov** [comment]
Error in    **в LayoutFarm.WebDom.Parser.CssParser.LexerEmitHandler(CssTokenName tkname, Int32 start, Int32 len) в c:\Projects\ToolsProjects\HtmlRenderer\pixelfarm\src\pixelfarm\paintlab.webdom\1_css_parser\CssParser.cs:строка 451**

**Comment by Karaulov** [comment]
after fix this, got error here:

   **в LayoutFarm.WebDom.Parser.CssParser.LexerEmitHandler(CssTokenName tkname, Int32 start, Int32 len) в c:\Projects\ToolsProjects\HtmlRenderer\pixelfarm\src\pixelfarm\paintlab.webdom\1_css_parser\CssParser.cs:строка 578**

**Comment by Karaulov** [comment]
after fix it, first demo html - opened!


But in svg test got error: 
![ex99jfq 1](https://user-images.githubusercontent.com/6445336/45362659-15541800-b5de-11e8-916a-51250b53897d.png)

**Comment by Karaulov** [comment]
**в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   в System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
   в System.Single.Parse(String s)
   в LayoutFarm.Svg.SvgParser.ParseMatrixArgs(String matrixTransformArgs) в c:\Projects\ToolsProjects\HtmlRenderer\pixelfarm\src\pixelfarm\paintlab.webdom\2_svg\SvgParser.cs:строка 471**

**Comment by Karaulov** [comment]
Possible to set culture globally?

**Comment by Karaulov** [comment]
@prepare Possible to set culture globally?

**Comment by prepare** [comment]
yes,

set on main thread


eg.=>
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-us");

**Comment by Karaulov** [comment]
But need help) Where located "main thread" ?)))

**Comment by prepare** [comment]
When you start the program (WinForm) => you are on main thread (UI thread)

eg.

public static void Main(){
    //....
    //.... some code ...

    System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-us");



    //.... some code ...
    //.... some code ...
}

**Comment by Karaulov** [comment]
YES! IT WORKS!

**Comment by Karaulov** [comment]
@prepare it can be fixed in HtmlHenderer ?

**Comment by prepare** [comment]
Yes, I 've updated it (float.Parse() ). 
(eg. https://github.com/PaintLab/PixelFarm/commit/1a978f9f0db2113aaba58a6c99ca8fbaa71d4af1)

and I will push to the master later.

**Comment by Karaulov** [comment]
@prepare WPF support very hard to be added ?(

**Comment by prepare** [comment]
At this time.

If you want to use my HtmlRenderer to WPF=>

As far as I know , 
There is way =>
see ...
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-and-windows-forms-interoperation
