### ISSUE TITLE
How to use it in WPF 

### ISSUE THREAD

**Issue by Karaulov** [LayoutFarm/HtmlRenderer#23]
I cant find HtmlRenderer.WPF for WPF support, this support only WinForms ???? 😡

**Comment by Karaulov** [comment]
👌

**Comment by prepare** [comment]
@Karaulov ,

I've read this ..

https://stackoverflow.com/questions/20719452/performance-of-writeablebitmapex-vs-drawingcontext

about 1 year ago.

and I've a plan for that. 


What do you think about it

**Comment by Karaulov** [comment]
But old version HTMLRENDERER can support WPF, it can't be moved from old to this version ?))

https://github.com/ArthurHub/HTML-Renderer/tree/master/Source/HtmlRenderer.WPF

**Comment by prepare** [comment]
This project was forked about 4 years ago. 
Many things have been changed (a lot).

WPF support need to _rewrite_ all again.
and
I have to admit that I'm not familiar with WPF .

So After I've read 
https://stackoverflow.com/questions/20719452/performance-of-writeablebitmapex-vs-drawingcontext

I plan to render on WPF with 'embeded' technique.

eg ...
1) use DirectXElement embeded in to WPF 
   (eg. https://www.scichart.com/, 
         https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-  
         direct3d9-content-in-wpf)
 
2) use WriteableBitmapEx eg.
    https://github.com/teichgraf/WriteableBitmapEx/

---

 one benefit is => it is easy to 'embeded' to other _engines_ 
(eg. .net core, game-engine)

**Comment by prepare** [comment]
But I also welcome any 'bring-WPF-to-live-again' contributors :)
