### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by corliss** [LayoutFarm/HtmlRenderer#4]
Hi - could you please add a few lines in README.md explaining how to build the project and sub-projects? Much appreciated!

**Comment by prepare** [comment]
OK, I' ll try. :)

**Comment by prepare** [comment]
I update missing project in MainDev.sln, readme.md
and I add a new wiki page about how to build the project
please see ...
https://github.com/LayoutFarm/HtmlRenderer/wiki/3.-Build-The-Project

**Comment by corliss** [comment]
Thanks. I just tried it with a fresh clone. There are eight build errors, all the same:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Resource' does not exist in the namespace 'LayoutFarm.Demo' (are you missing an assembly reference?)	HtmlRenderer.Demo	C:\HtmlRenderer\Source\HtmlRenderer.Demo\DemoForm.cs	423	Active

Any ideas? Thanks.

**Comment by corliss** [comment]
Looks like the namespace is wrong. Changing it from "LayoutFarm.Demo.Resource" to "HtmlRenderer.Demo.Resource" fixes it.
