### ISSUE TITLE
Won't build by default in VS 2019

### ISSUE THREAD

**Issue by tig** [LayoutFarm/HtmlRenderer#59]
Before I waste time trying to figure out why, are there some simple setup instructions I'm missing?

Severity	Code	Description	Project	File	Line	Suppression State
   Error	CS2001	Source file 

'C:\Users\ckindel\source\HtmlRenderer\Source\LayoutFarm.HtmlComposer\..\..\..\pixelfarm\src\pixelfarm\paintlab.webdom\1_css\CssDocument.cs' could not be found.	LayoutFarm.HtmlComposer	C:\Users\ckindel\source\HtmlRenderer\Source\LayoutFarm.HtmlComposer\CSC	1	Active

**Comment by prepare** [comment]
Today, I push an _easy-to-build_ repo here=> https://github.com/PaintLab/pxdev

How to build it=> see 'readme',
