### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by reginoprado** [LayoutFarm/HtmlRenderer#9]
Hello

I have this error I my widnows 10  when i tried to run the demo. VS2015 and VS2017:

System.DllNotFoundException occurred
  HResult=0x80131524
  Message=Unable to load DLL 'myft.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Other thing could you write example  to convert html to image? I need to render piece of HTML to image to be used in asp.net apps and i would like to use google fonts with link tag

I used before https://github.com/ArthurHub/HTML-Renderer  but the HTML and css is poor for what I need

Cheers

PD:
Other:
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'LayoutFarm.UI.UISurfaceViewportControl' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
TypeInitializationException: The type initializer for 'LayoutFarm.UI.UIPlatformWinForm' threw an exception.

Inner Exception 2:
BadImageFormatException: Could not load file or assembly 'PixelFarm.Drawing.Skia, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by prepare** [comment]
@reginoprado 

sorry for that inconvenient.

some parts of HtmlRenderer needs https://github.com/PaintLab/PixelFarm

---

**'myft'** is my cpp wrapper of FreeType , HarzBuff and some native image lib.

the **source code** of 'myft.dll' 
see => https://github.com/PaintLab/PixelFarm/tree/master/a_mini/external/myfonts

the **prebuilt binary, 32 bits** 
see => https://github.com/PaintLab/PixelFarm/tree/master/a_mini/external/dlls
 
---

for PixelFarm.Drawing.Skia , 

=> give me a time to review the code again.

**Comment by prepare** [comment]
@reginoprado 
> Other thing could you write example to convert html to image? 
I need to render piece of HTML to image to be used in asp.net apps and i would like to use google fonts with link tag

for your  server + asp.net apps,

Do you run it on your Windows 10?

**Comment by reginoprado** [comment]
Yes, windows 10

**Comment by prepare** [comment]
Hello, @reginoprado 

Sorry for late reply, 
many things have been update in the repo.

see this at https://github.com/LayoutFarm/HtmlRenderer/tree/2d9f221884bce8695bcca53cf12bb777c50c0d72

1. The latest update **dose not need 'myft.dll' anymore**,
    I remove it -- :)

and ...  2.
> ... Other thing could you write example to convert html to image? I need to render piece of HTML to image ...

---
How to Save Html Surface to a file
---

In this version, 
We can render to Win32 HDC surface (eg. Memory HDC)
and the save to the image file or
you can put the image's pixel buffer to another surface
eg OpenGL texture surface


![html_snap1](https://user-images.githubusercontent.com/7447159/33368542-91efa514-d524-11e7-9888-be59317293cc.png)
_pic 1: (1) run test3_MixHtml project, select 00.html example (2)_

---
![html_snap2](https://user-images.githubusercontent.com/7447159/33368545-922abaf0-d524-11e7-894f-553d845bd93e.png)

_pic 2: the test acid 1 screen_

---

![html_snap3](https://user-images.githubusercontent.com/7447159/33368546-927f4c5a-d524-11e7-850e-cd9e649953d1.png)

_pic 3: switch back to the main form, click 'save' button (3) to save the html screen to file_

---

Where is the file?, just see the code ...

![html_snap0](https://user-images.githubusercontent.com/7447159/33368547-92b5ad4a-d524-11e7-96e1-fef929d8ffb2.png)
_pic 4: the code behind that 'save' button_

the code above  works, but  just for example only.
I test it with WindowForms only.
But I think apply it to asp.net is not hard.
